apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: feature-tracker
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Rupa1277/argocd-demo.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true       # removes resources deleted from Git
      selfHeal: true     # reverts any manual/out-of-band cluster change
    syncOptions:
      - CreateNamespace=true